global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

remote_write:
  - url: "http://localhost:3000"
    basic_auth:
      username: "admin"
      password: "test123"

# NEURON_RT_VISIBLE_CORES